#!/usr/bin/env python3

import argparse
from pathlib import Path
import urllib.request
import subprocess
import os

parser = argparse.ArgumentParser(description="Run rules written using sgrep using Bento.")
parser.add_argument(
    "registry",
    type=str,
    help="An sgrep.live registry",
)

args = parser.parse_args()

def main():
    result = subprocess.run(
        [
            "docker",
            "run",
            "-v",
            f"{os.getcwd()}:/src",
            "-v",
            "/var/run/docker.sock:/var/run/docker.sock",
            "underyx/bento-registry",
            args.registry,
        ],
        encoding="utf-8",
        stderr=subprocess.STDOUT,
    )
    return result.returncode


if __name__ == "__main__":
    main()
