#!/usr/bin/env python3

import argparse
from pathlib import Path
import urllib.request

parser = argparse.ArgumentParser(description="Set up bento for report mode.")
parser.add_argument(
    "--config",
    type=str,
    default="default",
    help="name of a config or path to a config directory",
)

args = parser.parse_args()

CONFIG_URL_TEMPLATE = "https://github.com/returntocorp/bento-report/blob/master/configs/{config_name}/{config_file}?raw=true"


def fetch_file(path: Path):
    if "/" in args.config:
        # source is a local path
        source_url = f"file://{args.config}/{path.name}"
    else:
        source_url = CONFIG_URL_TEMPLATE.format(
            config_name=args.config, config_file=path.name
        )

    print(f"Fetching {path}'s content from {source_url}")

    with path.open("wb") as output_file:
        with urllib.request.urlopen(source_url) as response:
            output_file.write(response.read())


def main():
    root_dir = Path.cwd()
    (root_dir / ".bento").mkdir(exist_ok=True)
    fetch_file(root_dir / ".bentoignore")
    fetch_file(root_dir / ".bento" / "config.yml")


if __name__ == "__main__":
    main()
